/*
 * $HeadURL$
 * 
 * Copyright (c) 2010 MindTree Ltd. 
 * 
 * This file is part of Infix Maven Plugins
 * 
 * Infix Maven Plugins is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * Infix Maven Plugins is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with 
 * Infix Maven Plugins. If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.09 at 10:02:31 PM MST 
//

package com.mindtree.techworks.infix.pluginscommon.test.dummydirtree.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Directory" type="{http://mvn-infix.sourceforge.net/pluginscommon/test/dummydirtree}Directory" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "directory"
})
@XmlRootElement(name = "DirectoryTree")
public class DirectoryTree {

    @XmlElement(name = "Directory", required = true)
    protected List<DirectoryTree.Directory> directory;

    /**
     * Gets the value of the directory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the directory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirectory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DirectoryTree.Directory }
     * 
     * 
     */
    public List<DirectoryTree.Directory> getDirectory() {
        if (directory == null) {
            directory = new ArrayList<DirectoryTree.Directory>();
        }
        return this.directory;
    }
    
    /**
     * Describes a node
     * 
     * <p>Java class for Node complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="Node">
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "Node")
    @XmlSeeAlso({
        DirectoryTree.File.class,
        DirectoryTree.Directory.class
    })
    public static abstract class Node {

        @XmlAttribute(required = true)
        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }
    
    /**
     * The directory tree
     * 
     * <p>Java class for Directory complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="Directory">
     *   &lt;complexContent>
     *     &lt;extension base="{http://mvn-infix.sourceforge.net/pluginscommon/test/dummydirtree}Node">
     *       &lt;sequence>
     *         &lt;element name="Directory" type="{http://mvn-infix.sourceforge.net/pluginscommon/test/dummydirtree}Directory" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://mvn-infix.sourceforge.net/pluginscommon/test/dummydirtree}Node">
     *                 &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="SizeUnit" default="KB">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *                       &lt;enumeration value="B"/>
     *                       &lt;enumeration value="KB"/>
     *                       &lt;enumeration value="MB"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "Directory", propOrder = {
        "directory",
        "file"
    })
    public static class Directory
        extends DirectoryTree.Node
    {

        @XmlElement(name = "Directory")
        protected List<DirectoryTree.Directory> directory;
        @XmlElement(name = "File")
        protected List<DirectoryTree.File> file;

        /**
         * Gets the value of the directory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the directory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDirectory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Directory }
         * 
         * 
         */
        public List<DirectoryTree.Directory> getDirectory() {
            if (directory == null) {
                directory = new ArrayList<DirectoryTree.Directory>();
            }
            return this.directory;
        }

        /**
         * Gets the value of the file property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the file property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Directory.File }
         * 
         * 
         */
        public List<DirectoryTree.File> getFile() {
            if (file == null) {
                file = new ArrayList<DirectoryTree.File>();
            }
            return this.file;
        }
    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://mvn-infix.sourceforge.net/pluginscommon/test/dummydirtree}Node">
     *       &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="SizeUnit" default="KB">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="B"/>
     *             &lt;enumeration value="KB"/>
     *             &lt;enumeration value="MB"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class File
        extends DirectoryTree.Node
    {

        @XmlAttribute(name = "Size")
        protected BigDecimal size;
        @XmlAttribute(name = "SizeUnit")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String sizeUnit;

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSize(BigDecimal value) {
            this.size = value;
        }

        /**
         * Gets the value of the sizeUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSizeUnit() {
            if (sizeUnit == null) {
                return "KB";
            } else {
                return sizeUnit;
            }
        }

        /**
         * Sets the value of the sizeUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSizeUnit(String value) {
            this.sizeUnit = value;
        }

    }

}

