//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.09 at 10:02:31 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mvn-infix.sourceforge.net/pluginscommon/test/dummydirtree", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mindtree.techworks.infix.pluginscommon.test.dummydirtree.model;
