build:
  environment:
    sdkman:
      - java@17.0.8-tem
  nodes:
    analysis:
      tests:
        override:
          - java-scrutinizer-run
  tests:
    override:
      - command: ./gradlew --console=plain test jacocoRootReport
        coverage:
          file: 'build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml'
          format: 'jacoco'
